name: app_template
description: A new Flutter template.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: '>=2.18.5 <3.0.0' # % flutter --version => values of "Dart"
  flutter: '>=3.3.9'

dependencies:
  flutter:
    sdk: flutter
  app_settings: ^4.2.0
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.2
  flutter_modular: ^5.0.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.2.0
  riverpod_annotation: ^1.2.1

# flutter pub run build_runner build --delete-conflicting-outputs
dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  riverpod_generator: ^1.2.0

flutter_icons:
  android: 'launcher_icon'
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/ltmm1024x1024.png'
  macos:
    generate: true
    image_path: 'assets/images/ltmm1024x1024.png'
  web:
    generate: true
    image_path: 'assets/images/ltmm1024x1024.png'
  windows:
    generate: true
    image_path: 'assets/images/ltmm1024x1024.png'

flutter_gen:
  line_length: 132

flutter:
  uses-material-design: true
  assets:
   - assets/images/connor.072.png
